# Generated by Django 2.0.2 on 2018-08-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180813_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
    ]
