# Generated by Django 2.0.2 on 2018-08-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180813_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='initial_picture'),
        ),
    ]
